[package]
name = "ringbahn"
version = "0.1.0"
authors = ["Without Boats <woboats@gmail.com>"]
repository = "https://github.com/withoutboats/ringbahn"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
parking_lot = "0.10.2"
once_cell = "1.3.1"
futures-io = "0.3.5"
futures-core = "0.3.5"

[dependencies.iou]
git = "https://github.com/withoutboats/iou"
branch = "new-apis-needed-for-ringbahn"

[dev-dependencies]
futures = "0.3.5"
